services:
  server:
    image: server:latest
    container_name: spring_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "${DB_URL}"
      SPRING_DATASOURCE_USERNAME: "${DB_USER}"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "${DB_DDL}"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge