name: CI/CD Pipeline Spring Application to VPS.

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code.
        uses: actions/checkout@v2

      - name: Transfer Application files to VPS.
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -o StrictHostKeyChecking=no -r * ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/list_app/server/

      - name: SSH to VPS.
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd ~/list_app/server/
            docker-compose down
            docker-compose up -d
