name: CI/CD Pipeline Spring Application to VPS.

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code.
        uses: actions/checkout@v2

      - name: Build Docker image.
        run: docker build -t spring_app:${{ github.sha }} .

      - name: Save Docker image to file.
        run: docker save -o spring_app.tar spring_app:${{ github.sha }}

      - name: Transfer Docker image and compose to VPS.
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -o StrictHostKeyChecking=no spring_app.tar ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/list_app/server/
          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/list_app/server/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH to VPS and load Docker image.
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd ~/list_app/server/
            docker load -i spring_app.tar
            docker-compose down
            docker-compose up -d