name: CI Tests.

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    environment: production

    env:
      MYSQL_ROOT_PASSWORD: ${{ secrets.TEST_ROOT_PASSWORD }}
      DB_NAME: ${{ secrets.TEST_DB_NAME }}
      DB_USER: ${{ secrets.TEST_DB_USER }}
      DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
      DB_URL: ${{ secrets.TEST_DB_URL }}
      JWT_SECRET_KEY: ${{ secrets.TEST_JWT_SECRET_KEY }}
      STORAGE_LOCATION_DIRECTORY: ${{ secrets.TEST_STORAGE_LOCATION_DIRECTORY }}

    steps:
      - name: Checkout code.
        uses: actions/checkout@v2

      - name: Set up Docker Buildx.
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose.
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Build and start Docker containers.
        run: docker-compose up --build -d

      - name: Wait for mySQL to be ready.
        run: |
          for i in {1..10}; do
            if docker exec mysql_db mysqladmin ping -h"localhost" --silent; then
              echo "mySQL is up !"
              break
            fi
            echo "Waiting for mySQL..."
            sleep 5
          done

      - name: Run Tests.
        run: docker exec spring_app ./mvnw test

      - name: Stop Docker containers.
        run: docker-compose down -v